### ISSUE TITLE
Who should be our lead maintainer?

### ISSUE THREAD

**Issue by josephholsten** [chef-brigade/mongodb-cookbook#33]
The thinking in https://github.com/chef-brigade/meta/issues/2 is that each project should have one-and-only-one lead maintainer. @jamesonjlee certainly filled that role well for quite a while, but he can't devote as much time any more.

I'll support any selection procedure that: a) is non-violent & b) does not select me.

So who wants to shepherd this thing?

**Comment by zarry** [comment]
@josephholsten We don't seem to be getting much traction on finding a specific owner.  Maybe we take a different approach to try and get some traction and progress with the mongodb cookbook.

I am suggesting we appoint 3 maintainers to the mongo cookbook and try to move forward like that.  These can be maintainers/mergers whatever we want to call it, but at the moment they are tasked with helping drive this cookbook forward and cleaning up all the cruft. 

That being said I feel comfortable being one of a group of maintainers on the cookbook.  I am not sure I would be able to dedicate the type of time to "own" the cookbook.

**Comment by josephholsten** [comment]
Ok, I'll "own" it for the immediate future. But you don't need my approval to do awesome. If a PR looks good, I trust you!

**Comment by rex** [comment]
@josephholsten I apologize for not seeing this more quickly. I'd really like to assume the lead for this cookbook as I use MongoDB heavily in personal and work projects and have a vested interest in making this the best it can be.

**Comment by zarry** [comment]
:+1: for @rex

**Comment by rex** [comment]
Aw shucks @zarry :smile: :rocket:

**Comment by josephholsten** [comment]
@rex sounds great. @luishdez has also been helping quite a bit, I'm mentioning him so he sees this.

Could you submit a PR adding your name as maintainer to the `README.md`?

**Comment by josephholsten** [comment]
@rex you're added as an owner to chef-brigade. Thanks for taking this off my plate!

**Comment by rex** [comment]
@josephholsten Done! https://github.com/chef-brigade/mongodb-cookbook/pull/42

Thank you for letting me take it off your plate :)

**Comment by josephholsten** [comment]
closing. If you need anything else, let me know!
