### ISSUE TITLE
Fix compatibility with ruby 1.9.3

### ISSUE THREAD

**Issue by luishdez** [chef-brigade/mongodb-cookbook#34]
In order to have a clean start with CI we should fix the compatibility with ruby 1.9.3

https://travis-ci.org/edelight/chef-mongodb/jobs/59349011

```sh
Gem::InstallError: ohai requires Ruby version >= 2.0.0.
An error occurred while installing ohai (8.2.0), and Bundler cannot continue.
Make sure that `gem install ohai -v '8.2.0'` succeeds before bundling.
```

Options: set `gem 'ohai', '< 8.0.0'` or remove support for ruby 1.9.3

**Comment by josephholsten** [comment]
what release of chef ships with 1.9.3? I know it's at [end of life](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/)

Just chef 11, right? https://www.chef.io/blog/2014/11/25/ruby-1-9-3-eol-and-chef-12/

**Comment by luishdez** [comment]
That's right. Ruby EOL for 1.9.3 has ended in February as well and it won't receive any security fix anymore. May be we should tag a new release and drop support for 1.9.3

**Comment by luishdez** [comment]
This PR https://github.com/chef-brigade/mongodb-cookbook/pull/27 has solve the problem, as it sets a condition for ruby version in Gemfile
