### ISSUE TITLE
Run Travis on all open PRs

### ISSUE THREAD

**Issue by josephholsten** [chef-brigade/mongodb-cookbook#35]
I'd like us to start making progress, so it would be awesome to know which PRs can be merged. Step one: get travis running our tests.

@luishdez what's outstanding for this?

**Comment by luishdez** [comment]
@josephholsten In order to trigger travis… I think I'll have to update all PRs because those exists before the travis setup. No sure if there is another way to trigger travis in old PRs

We should check https://github.com/chef-brigade/mongodb-cookbook/issues/34 before triggering as well

**Comment by luishdez** [comment]
Ok I think we can create a /develop branch to test merges and trigger travis

**Comment by luishdez** [comment]
OK!  I just found out that if you close and open again the PR re-triggers travis :)
