### ISSUE TITLE
Support YAML config file

### ISSUE THREAD

**Issue by josephholsten** [chef-brigade/mongodb-cookbook#72]
From https://github.com/edelight/chef-mongodb/issues/309

Per the mongo doc for [Configuration Options](http://docs.mongodb.org/manual/reference/configuration-options/):

> Changed in version 2.6: MongoDB introduces a YAML-based configuration file format. The 2.4 configuration file format remains for backward compatibility.

It also moves the options to totally different locations.

Obviously, this is a breaking change.

**Comment by luishdez** [comment]
Done in mongodb-v3 branch https://github.com/chef-brigade/mongodb-cookbook/pull/86/files
