### ISSUE TITLE
MongoDB without NUMA fails to start

### ISSUE THREAD

**Issue by jrstarke** [chef-brigade/mongodb-cookbook#89]
I'm using the `mongodb::10gen_repo` and `mongodb::replicaset` cookbooks on Ubuntu 14.04. After preparing and cooking a machine, the system would provision and Mongo db would not have started. 

When I looked into the problem, I found that I would have the following error in my `/var/log/upstart/mongodb.log`

```
start-stop-daemon: unrecognized option '--config'
Try 'start-stop-daemon --help' for more information.
```

After spending a lot of time disecting `debian-mongodb.upstart.erb` the resulting init, and how it would run, I think I found the problem. In the block to handle NUMA support, when we don't have NUMA we set  `DAEMON_OPTS="-- $DAEMON_OPTS"`. `$DAEMON_OPTS` does not appear to be set in the template, and I eventually found that it is set in the `@sysconfig_file` in the block below. As a result, we blow away the `-- ` that we specifically added.  By moving the NUMA support below the sysconfig_file block, it seems to work as expected.

**Comment by luishdez** [comment]
Thanks for the PR!
